Frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/src/**/*'

Backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/src/**/*.go'

CronTasks:
  - changed-files:
      - any-glob-to-any-file: 'backend/tasks/*.go'

ProviderMiddleware:
  - changed-files:
      - any-glob-to-any-file: 'provider-middleware/*.go'

Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

Other-Config:
- changed-files:
  - any-glob-to-any-file: "config/*"

HAS_MIGRATION:
- changed-files:
  - any-glob-to-any-file: 'backend/migrations/*.sql'

CI-Actions:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/*.yml'
