apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.__CONFIG__ = {
      state: {{ .Values.frontendConfig.state | quote }},
      deployment: {{ .Values.frontendConfig.deployment | quote }},
      posthogKey: {{ .Values.frontendConfig.posthogKey | quote }},
      posthogHost: {{ .Values.frontendConfig.posthogHost | quote }}
    };
