apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - args: ["-g daemon off;"]
          image:                    # OCI container image registry location
          name: frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: config 
              subPath: nginx.conf
            - mountPath: /var/log/nginx/
              name: logs
      restartPolicy: Always
      imagePullSecrets:
        - name: ecr-secret
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: config
          configMap:
            name: nginx-config
