apiVersion: batch/v1
kind: Job
metadata:
  name: kratos-migrate
  labels:
    app: kratos
spec:
  template:
    spec:
      containers:
        - name: kratos-migrate
          image: oryd/kratos:v1.1.0
          command: ["kratos", "migrate", "-c", "/etc/config/kratos/kratos.yml", "sql", "-e", "--yes"]
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos-dsn 
                  key: KRATOS_DSN
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/config/kratos/kratos.yml
              subPath: kratos.yml
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: OnFailure
      volumes:
        - name: kratos-config
          configMap:
            name: kratos-config
  backoffLimit: 4
