apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats-server.conf: |
    jetstream: enabled
    port: 4222
    monitor_port: 8222

    jetstream {
       store_dir: /data
       max_mem: 1G
       max_file: 5G
    }
