root = "."
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/main backend/cmd/main.go"
bin = "bin/main"
include_dir = ["backend"]
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
log = "logs/air.log"
stop_on_error = true
send_interrupt = true
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
