root = "."
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/cron_tasks /app/backend/tasks/."
bin = "bin/cron_tasks"
include_dir = ["backend", "backend/tasks"]
include_file = []
exclude_dir = ["frontend", "provider-middleware"]
exclude_regex = ["_test\\.go", "frontend/.*", "provider-middleware/.*"]
exclude_unchanged = true

log = "logs/tasks.air.log"
stop_on_error = true
send_interrupt = true
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
