#!/bin/bash

help="Usage: ./build [up] [--migrate-fresh]"

if [[ "$1" == "-h" ]]; then
	echo "$help"
	exit 0
fi

echo "Building backend..."

if [[ "$1" == "up" ]]; then
	if [[ -z "$(docker ps -q)" ]]; then
		docker-compose up -d
	fi
	if [[ "$2" == "--migrate-fresh" ]]; then
		sleep 3
		go run migrations/main.go
	fi
	go run backend/main.go
	exit 0
fi

if [[ "$1" == "--migrate-fresh" ]]; then
	go run migrations/main.go
fi
go run backend/main.go
exit 0
