#!/bin/bash

help="Usage: ./build up | migrate-fresh | server"

if [[ "$1" == "-h" ]]; then
	echo "$help"
	exit 0
fi

if [[ "$1" == "up" ]]; then
	docker-compose up -d --build
	echo "Building backend..."
fi

if [[ "$1" == "migrate-fresh" ]]; then
	go run backend/migrations/main.go
fi

if [[ "$1" == "server" ]]; then
	go run backend/main.go
fi

exit 0
