{
 "title": "Backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number Of Requests",
   "type": "stat",
   "description": "Number of user requests per API endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  floor(\r\n    sum by (rs_path) (\r\n      (\r\n        label_replace(\r\n          increase(http_requests_total{path=~\"^/api/proxy/libraries/.*\"}[$__range]),\r\n          \"rs_path\", \"/api/proxy/libraries\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_requests_total{path=~\"^/api/libraries/[0-9]+(/toggle|/favorite)?$\"}[$__range]),\r\n          \"rs_path\", \"/api/libraries/#\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_requests_total{path=~\"^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n          \"rs_path\", \"/api/videos/#\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_requests_total{path!~\"^/api/proxy/libraries/.*|^/api/libraries/[0-9]+(/toggle|/favorite)?$|^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n          \"rs_path\", \"$1\", \"path\", \"^(.*)$\"\r\n        )\r\n      )\r\n    )\r\n  ) > 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code Error Counts",
   "type": "table",
   "description": "Lists the count of status code errors per API endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(\r\n  floor(\r\n    sum by (rs_path, method, status_code) (\r\n      (\r\n        label_replace(\r\n          increase(http_response_status_total{path=~\"^/api/proxy/libraries/.*\", status_code=~\"4..|5..\"}[$__range]),\r\n          \"rs_path\", \"/api/proxy/libraries\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_response_status_total{path=~\"^/api/libraries/[0-9]+(/toggle|/favorite)?$\", status_code=~\"4..|5..\"}[$__range]),\r\n          \"rs_path\", \"/api/libraries/#\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_response_status_total{path=~\"^/api/videos/[0-9]+(/visibility|/favorite)?$\", status_code=~\"4..|5..\"}[$__range]),\r\n          \"rs_path\", \"/api/videos/#\", \"path\", \".*\"\r\n        )\r\n      )\r\n      or\r\n      (\r\n        label_replace(\r\n          increase(http_response_status_total{path!~\"^/api/proxy/libraries/.*|^/api/libraries/[0-9]+(/toggle|/favorite)?$|^/api/videos/[0-9]+(/visibility|/favorite)?$\", status_code=~\"4..|5..\"}[$__range]),\r\n          \"rs_path\", \"$1\", \"path\", \"^(.*)$\"\r\n        )\r\n      )\r\n    )\r\n  ) > 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "bargauge",
   "description": "Average response time of the user requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rs_path) (\r\n  label_replace(\r\n    increase(http_request_duration_seconds_sum{path=~\"^/api/proxy/libraries/.*\"}[$__range]),\r\n    \"rs_path\", \"/api/proxy/libraries\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_sum{path=~\"^/api/libraries/[0-9]+(/toggle|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"/api/libraries/#\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_sum{path=~\"^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"/api/videos/#\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_sum{path!~\"^/api/proxy/libraries/.*|^/api/libraries/[0-9]+(/toggle|/favorite)?$|^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"$1\", \"path\", \"^(.*)$\"\r\n  )\r\n)\r\n/\r\nsum by (rs_path) (\r\n  label_replace(\r\n    increase(http_request_duration_seconds_count{path=~\"^/api/proxy/libraries/.*\"}[$__range]),\r\n    \"rs_path\", \"/api/proxy/libraries\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_count{path=~\"^/api/libraries/[0-9]+(/toggle|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"/api/libraries/#\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_count{path=~\"^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"/api/videos/#\", \"path\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    increase(http_request_duration_seconds_count{path!~\"^/api/proxy/libraries/.*|^/api/libraries/[0-9]+(/toggle|/favorite)?$|^/api/videos/[0-9]+(/visibility|/favorite)?$\"}[$__range]),\r\n    \"rs_path\", \"$1\", \"path\", \"^(.*)$\"\r\n  )\r\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"server\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests By Time Of Day (/api/libraries/search)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{path=\"/api/libraries/search\"}[10m]))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request duration (Backend) over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time(http_request_duration_seconds_count{service=\"server\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go GC heap allocations total (node)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(go_gc_heap_allocs_bytes_total{node_role_kubernetes_io_master=\"true\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * FROM login_activity LIMIT 50 "
    }
   ]
  },
  {
   "title": "Memory usage - Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "changes(container_memory_usage_bytes{container=\"unlockedv2\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by(path) (rate(http_response_status_total{service=\"server\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (HTTP 400+)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "count_over_time(http_errors_total{service=\"server\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}