{
 "title": "Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Favorites Per Content Type",
   "type": "table",
   "description": "Display total number of favorites per content type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from (\r\nselect 'Libraries' as content_type, count(f.id) from open_content_favorites f\r\nJOIN open_content_providers ocp ON ocp.id = f.open_content_provider_id\r\n        AND ocp.currently_enabled = TRUE\r\n        AND ocp.deleted_at IS NULL\r\nJOIN libraries lib ON lib.open_content_provider_id = ocp.id \r\n        AND lib.id = f.content_id\r\nUnion all\r\nselect 'Videos' as content_type, count(f.id) from open_content_favorites f\r\nJOIN open_content_providers ocp ON ocp.id = f.open_content_provider_id\r\n        AND ocp.currently_enabled = TRUE\r\n        AND ocp.deleted_at IS NULL\r\nJOIN videos vid ON vid.open_content_provider_id = ocp.id \r\n        AND vid.id = f.content_id\r\nunion all\r\nselect 'Helpful Links' as content_type, count(f.id) from open_content_favorites f\r\nJOIN open_content_providers ocp ON ocp.id = f.open_content_provider_id\r\n        AND ocp.currently_enabled = TRUE\r\n        AND ocp.deleted_at IS NULL\r\nJOIN helpful_links hel ON hel.open_content_provider_id = ocp.id \r\n        AND hel.id = f.content_id\r\n) order by 2 desc;\r\n"
    }
   ]
  },
  {
   "title": "Total Number Of Logins By Facility",
   "type": "table",
   "description": "Displays total number of logins by facility.",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    f.name AS facility,\r\n    SUM(la.total) AS logins\r\nFROM login_metrics la\r\nINNER JOIN users u ON u.id = la.user_id\r\nINNER JOIN facilities f ON f.id = u.facility_id\r\nGROUP BY f.name;"
    }
   ]
  },
  {
   "title": "Features Per User",
   "type": "table",
   "description": "Displays the number of features per user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select u.username, count(ocf.id) num_of_features  from open_content_favorites ocf \r\n\r\ninner join users u on u.id = ocf.user_id \r\ninner join facilities f on f.id = u.facility_id\r\n\r\nwhere ocf.facility_id is not null\r\n\r\ngroup by u.username\r\n;"
    }
   ]
  },
  {
   "title": "Favorites Per User",
   "type": "table",
   "description": "Displays the number of favorites per user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select u.username, count(ocf.id) num_of_favs  from open_content_favorites ocf \r\n\r\ninner join users u on u.id = ocf.user_id \r\ninner join facilities f on f.id = u.facility_id\r\n\r\nwhere ocf.facility_id is null\r\n\r\ngroup by u.username\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Logins Per Week",
   "type": "table",
   "description": "Displays total user logins per week",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT f.name, SUM(la.total_logins) as total, \r\n    DATE_TRUNC('week', la.time_interval) as start_week\r\nFROM login_activity la\r\nINNER JOIN facilities f ON f.id = la.facility_id\r\nGROUP BY f.name, 3\r\nORDER BY f.name, 3 DESC;\r\n"
    }
   ]
  },
  {
   "title": "Logins Per Hour",
   "type": "table",
   "description": "Displays the total logins per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select f.name, la.total_logins, time_interval from login_activity la\r\n\r\ninner join facilities f on f.id = la.facility_id\r\n\r\norder by f.name, la.time_interval desc;"
    }
   ]
  },
  {
   "title": "Logins Per Day",
   "type": "table",
   "description": "Displays the total user logins per day.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select  date(la.time_interval), f.name, sum(la.total_logins) total from login_activity la\r\n\r\ninner join facilities f on f.id = la.facility_id\r\n\r\ngroup by f.name, date(la.time_interval)\r\norder by 1 desc, f.name\r\n;"
    }
   ]
  },
  {
   "title": "User Logins",
   "type": "table",
   "description": "Displays the number of logins per user along with their last login date/time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "select u.username, f.name, la.total, la.last_login from login_metrics la\r\n\r\ninner join users u on u.id = la.user_id\r\ninner join facilities f on f.id = u.facility_id\r\n\r\norder by f.name, la.total desc\r\n;"
    }
   ]
  },
  {
   "title": "login times",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT * FROM login_activity LIMIT 50 "
    }
   ]
  }
 ]
}