CREATE USER hydra WITH PASSWORD 'ChangeMe!';
CREATE DATABASE hydra;
GRANT ALL PRIVILEGES ON DATABASE hydra TO hydra;

CREATE USER kratos WITH PASSWORD 'ChangeMe!';
CREATE DATABASE kratos;
GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;

CREATE USER keto WITH PASSWORD 'ChangeMe!';
CREATE DATABASE keto;
GRANT ALL PRIVILEGES ON DATABASE keto TO keto;
