#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
git diff --cached --name-only --diff-filter=ACMRTUXB >.husky/staged-files
npx lint-staged
npx oxlint --fix
./vendor/bin/pint
git add $(cat .husky/staged-files)
