name: UnlockedV2 Changelog generation
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0 * * FRI
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --verbose --exclude-path '.github/**'
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
