name: Migration check

on:
  workflow_dispatch:
  pull_request: 
    branches: ["main"]
      

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changed migration files
        id: check_diff
        run: |
          echo "CHANGED=$(git diff --name-only origin/main | grep '^backend/migrations/' || true)" >> "$GITHUB_OUTPUT"

      - name: Skip if no migration files changed
        if: steps.check_diff.outputs.CHANGED == ''
        run: echo "✅ No migration files changed. Skipping migration check."

      - name: Check duplicate migration files
        if: steps.check_diff.outputs.CHANGED != ''
        run: |
          echo "🛠️ Checking for duplicate migration files..."
          DUPLICATE_MIGRATIONS=$(ls -1 backend/migrations | grep '.*\.sql' | cut -c1-5 | sort | uniq -d)
          if [ -z "$DUPLICATE_MIGRATIONS" ]; then
            echo "✅ No duplicate migration files found."
          else
            echo "🚨 Duplicate migration files found 🚨"
            echo "Migration number(s): $DUPLICATE_MIGRATIONS"
            exit 1
          fi
