name: Migration check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'backend/migrations/**'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check duplicate migration files
        run: |
          DUPLICATE_MIGRATIONS=$(ls -1 backend/migrations | grep '.*\.sql' | cut -c1-5 | sort | uniq -d)
          if [ -z "$DUPLICATE_MIGRATIONS" ]; then
            echo "no invalid migrations found"
          else
            echo "🚨 Duplicate migration files found 🚨"
            echo "Migration number: $DUPLICATE_MIGRATIONS is a duplicate\n and needs to be renamed"
            exit 1
          fi
